Replace Jumphosts for Load Testing (#5202)
* Initial configuration of locust role

* Adding changelog and readme to locust cookbook.

* Adding identity-locust reciepes to BerksFile

* Setting specific version for python-pip-whl due to compatiablity error

* Purging python-pip-whl prior to reinstallation

* WIP: Initial configuration of loadtesting module

* Filtering out prompt skip flag from extra options passed to locust

* Correct -p parameter for id-locust execution

* Modifying locust-leader and worker documents

* WIP: Adding focust utility and updating pocust to work with ssm documents

* WIP: Updating loadtesting cli tools and ssm scripts

* Removing [scp|ssh]-instance utilities

* Updating IP address reported by id-locust

* Adding cleanup to locust-leader-footprint document

* Setting loadtest flag as false by default, setting ssm docs as conditionally created by flag

* Terraform format and setting loadtest variables

* Terraform format

* Adding TMOUT env variable to locust-leader execution

* Terraform Format

* Removing identity-locust readme

* Re-adding identity-locust README

* Removing unused identity-locust attributes

* Switching from ELB health checks to EC2

* Updating SSM module to latest version

* Updating locust security group for consistent tf plans

* Converting locust_loadtesting module to flat .tf files

diff --git a/bin/pocust b/bin/pocust
--- a/bin/pocust
+++ b/bin/pocust
@@ -11,29 +11,20 @@ set -euo pipefail
 
 . "$(dirname "$0")/lib/common.sh"
 
-# List of Git repos to check SHAs in
-IDPREPOS="/etc/login.gov/repos/identity-devops /etc/login.gov/repos/identity-devops-private /srv/idp/current"
-
-# Files to fingerprint
-IDPFILES="/srv/idp/current/config/application_s3_env.yml /srv/idp/current/config/application.yml"
-
 # Collect loadtest repo info for identifying version of test suite
-LMREPOS="identity-loadtest"
 
 usage () {
-  cat >&2 <<EOM
-usage: $0 RUN_NAME ENVIRONMENT [LOCUST_MASTER]
+    cat >&2 <<EOM
+usage: $0 RUN_NAME ENVIRONMENT
 
 RUN_NAME      - Slugified (no spaces!) name for test run.  Example:
                 sign_in-w1-c500-n1000
 ENVIRONMENT   - pt, pt2, etc
-LOCUST_MASTER - Instance name of where Locust master was during the
-                test.  (If omitted, Locust results are not gathered)
-                
+
 This script will save data into ~/<ENVIRONMENT>-<RUN_NAME>-<TIMESTAMP> on on your
 local machine.
 
-Example:  $0 sign_in-w14-c1000 pt i-0eeb2eb0e831795fe
+Example:  $0 sign_in-w14-c1000 pt
 
 Gathers:
 * List of instances
@@ -49,79 +40,73 @@ EOM
 }
 
 if [ $# -lt 2 ]; then
-  usage
-  exit 1
+    usage
+    exit 1
 fi
 
 TS=$(date -u +%Y%m%d%H%M%S)
 RUN_NAME=${1}
 ENV=${2}
-LOCUST_MASTER=${3-}
-ODIR="${HOME}/${ENV}-${RUN_NAME}-${TS}"
-
-define IDPSCRIPT <<EOM
-echo "# Repositories" > \${HOME}/\${HOSTNAME}-pocust.txt
-for r in ${IDPREPOS}; do
-  cd "\${r}"
-  echo -n "\${r}: " >> \${HOME}/\${HOSTNAME}-pocust.txt
-  git describe --always --tags >> \${HOME}/\${HOSTNAME}-pocust.txt
-done
-echo "# IdP deploy.json" >> \${HOME}/\${HOSTNAME}-pocust.txt
-cat /srv/idp/current/public/api/deploy.json >> \${HOME}/\${HOSTNAME}-pocust.txt
-echo "# Configurations" >> \${HOME}/\${HOSTNAME}-pocust.txt
-for f in ${IDPFILES}; do
-  sudo sha256sum --tag "\$f" >> \${HOME}/\${HOSTNAME}-pocust.txt
-done
-EOM
-
-define LMSCRIPT <<EOM
-rm -rf ~/pocust
-mkdir ~/pocust
-echo "# Repositories" > \${HOME}/pocust/\${HOSTNAME}-pocust.txt
-for r in ${LMREPOS}; do
-  cd /etc/login.gov/repos/\$r
-  echo -n "\${r}: " >> \${HOME}/pocust/\${HOSTNAME}-pocust.txt
-  git describe --always --tags >> \${HOME}/pocust/\${HOSTNAME}-pocust.txt
-done
-echo "# Collecting all locust output files"
-cp /var/log/loadtest/* ~/pocust/
-EOM
+ODIR="${HOME}/${RUN_NAME}-${ENV}-${TS}"
 
 echo "Creating ${ODIR}"
 mkdir "${ODIR}"
 
 echo "Getting full instance list"
-bin/ls-servers -q -b -e ${ENV} > "${ODIR}/running-instances.tab"
+bin/ls-servers -q -b -e "${ENV}" > "${ODIR}/running-instances.tab"
 
 echo "Getting running IdP instance list with health status"
-bin/ls-servers -q -b -e ${ENV} -r idp > "${ODIR}/running-idp-health.tab"
+bin/ls-servers -q -b -e "${ENV}" -r idp > "${ODIR}/running-idp-health.tab"
 
 IDPTOP=$(cat "${ODIR}/running-idp-health.tab" | egrep '^i-' | head -1 | awk '{ print $1 }')
 
 if [ -z "${IDPTOP}" ]; then
-  # Thought - Could cleanup directory here, but don't want to presume
-  # it is unwanted.  Left to the user.
-  raise "Failed to find IdP instance - Aborting"
+    # Thought - Could cleanup directory here, but don't want to presume
+    # it is unwanted.  Left to the user.
+    raise "Failed to find IdP instance - Aborting"
 fi
 
-echo "Footprinting ${IDPTOP}"
-bin/ssh-instance ${IDPTOP} "${IDPSCRIPT}"
+echo "Footprinting IDP Instance ${IDPTOP}"
+IDP_FOOTPRINT=$(
+aws ssm send-command \
+    --instance-ids "${IDPTOP}" \
+    --document-name "${ENV}-ssm-cmd-idp-footprint" |
+    jq -r '.Command.CommandId')
 
-echo "Gathering data from ${IDPTOP}"
-bin/scp-instance ${IDPTOP}:~/*-pocust.txt "${ODIR}/"
+LEADER_ID=$(\
+    aws autoscaling describe-auto-scaling-groups \
+    --auto-scaling-group-name "$ENV-locust-leader" |
+    jq -r '.AutoScalingGroups[].Instances[].InstanceId'
+)
+
+echo "Footprinting Locust Leader ${LEADER_ID}"
+LEADER_FOOTPRINT=$(
+aws ssm send-command \
+    --targets "Key=tag:Name,Values=asg-${ENV}-locust-leader" \
+    --document-name "${ENV}-ssm-cmd-locust-leader-footprint" |
+    jq -r '.Command.CommandId'
+)
 
 echo "Getting applied terraform/app version"
 bin/deploy/get-version-info.sh ${ENV} > "${ODIR}/terraform-app-version.txt"
 
-if [ ! -z "${LOCUST_MASTER}" ]; then
-  echo "Footprinting ${LOCUST_MASTER}"
-  bin/ssh-instance ${LOCUST_MASTER} "${LMSCRIPT}"
+aws ssm wait command-executed \
+    --command-id "$IDP_FOOTPRINT" \
+    --instance-id "$IDPTOP"
 
-  echo "Gathering data from ${LOCUST_MASTER}"
-  bin/scp-instance ${LOCUST_MASTER}:~/pocust/* "${ODIR}/"
+aws ssm wait command-executed \
+    --command-id "$LEADER_FOOTPRINT" \
+    --instance-id "$LEADER_ID"
 
-  echo "Cleaning up ${LOCUST_MASTER}"
-  bin/ssh-instance ${LOCUST_MASTER} 'rm -rf ${HOME}/pocust; rm -f /var/log/load_test/*'
-fi
+echo "Gathering data from Transfer Utility"
+#aws s3 cp \
+#    s3://login-gov.transfer-utility.$(aws sts get-caller-identity | jq -r '.Account')-us-west-2/${ENV}/out/pocust/ \
+#    "${ODIR}/ --recursive"
+
+aws s3 cp \
+    "s3://login-gov.transfer-utility.$(\
+    aws sts get-caller-identity |
+    jq -r '.Account')-us-west-2/$ENV/out/pocust/" \
+    "${ODIR}/" --recursive
 
 echo "Done!  Now send ${ODIR} to a good place"
