Move all of env.sh into identity-devops-private. (#350)
* Lint check-required-files.sh

- Improve curl safety with -f, so it doesn't proceed after failure.
- Fix all shellcheck warnings.

* Switch to using id-devops-private for ALL vars.

- Change the contract of get-private-env.sh. Instead of accepting an
  ENV_NAME and returning a single file path, accept no arguments and
  return the directory containing all the environment files. It is the
  caller's responsibility to know to source default.sh and then $ENV.sh.
- Change load-env.sh so that it sources default.sh and $ENV.sh from the
  identity-devops-private repo. Do not source env.sh from this repo. But
  support the old behavior if the user specifies an env file path on the
  command line, in which case source that file exclusively.
- In bootstrap.sh, don't pass any env path. (It was already optional.)
- In `deploy`, fix shellcheck warnings, don't pass an explicit env path,
  and improve error and log messages.
- Add some useful helpers to common.sh to improve logging.

* Add functionality to enforce that env is recent.

- Add ID_ENV_COMPAT_VERSION to the private default.sh.
- Add ENFORCED_ENV_COMPAT_VERSION to determine what versions are
  acceptable. You can increment this value in order to ensure that users
  are running a version of the env config >= this value.
- The effect of this change will be to enforce that folks are using the
  new identity-devops-private env config, or at least have gone to the
  trouble of setting the ID_ENV_COMPAT_VERSION to claim that they have
  new enough config.

* Add join_by and array_to_string to lib/common.sh.

This is in preparation for removing these functions from the env config
files.

* Guide users through the private env migration.

- If env/env.sh exists, tell the user about the migration to private,
  git tracked environment variables that is being done with this pull
  request.
- Offer to move env.sh to env.sh.backup to skip this message.

* Fix ID_ENV_COMPAT_VERSION check.

* Add more docs on how all of the env stuff works.

* Load-env.sh: don't assume we're set -e.

* Do env inheritance in identity-devops-private.

Previously, we would rely on `load-env.sh` to source `default.sh` and
then `$ENV.sh`. Instead, rely on the env files in
identity-devops-private/env/ to manage their own inheritance explicitly.

Now load-env.sh will only ever source a single file:

- If an env-specific file exists, source that.
- Otherwise, source `default.sh` and print a warning.

Also increment the ENFORCED_ENV_COMPAT_VERSION.

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # function to exit process with error message
-die() { echo "$@" 1>&2 ; exit 1; }
+die() { echo_red "$*" >&2 ; exit 1; }
 
 # http://redsymbol.net/articles/unofficial-bash-strict-mode/
 set -euo pipefail
@@ -22,13 +22,14 @@ ENVIRONMENT=$1; shift
 GSA_USERNAME=$1; shift
 TF_DIR=$1; shift
 TF_CMD=("$@")
-ENVIRONMENT_CONFIG=env/env.sh
 
 # We need to be in the root of the repo for all this to work.
 cd "$(dirname "$0")"
 
+echo_blue "deploy environment: $ENVIRONMENT"
+
 echo "DEPLOY: Loading environment variables...."
-. bin/load-env.sh "$ENVIRONMENT" "$GSA_USERNAME" "$ENVIRONMENT_CONFIG"
+. bin/load-env.sh "$ENVIRONMENT" "$GSA_USERNAME"
 
 # Check that current version of terraform is supported by our environment. This
 # array should be set in the environment-specific variables.
@@ -39,25 +40,30 @@ run bin/check-required-files.sh "$ENVIRONMENT"
 
 if [ -z "${TF_VAR_chef_id:=}" ] ; then
     die "You must specify an initial chef user.  \
-Make sure $ENVIRONMENT_CONFIG contains all the necessary configuration."
+Make sure $ID_ENV_DIR/$ENVIRONMENT.sh contains all the necessary configuration."
 fi
 
 if [ -z "${TF_VAR_chef_id:=}" ] ; then
     die "You must specify an environment to terraform.  \
-Make sure $ENVIRONMENT_CONFIG contains all the necessary configuration."
+Make sure $ID_ENV_DIR/$ENVIRONMENT.sh contains all the necessary configuration."
 fi
 
 STATE=${TF_DIR}/terraform-${TF_VAR_env_name}.tfstate
-if [ "${TF_DIR}" == "terraform-dns" -o "${TF_DIR}" == "terraform-cloudtrail" ]; then
-    echo "Not using a region specific state file for dns remote config"
-    STATE=${TF_DIR}/terraform.tfstate
-fi
+case "$TF_DIR" in
+    terraform-dns|terraform-cloudtrail)
+        echo "Not using a region specific state file for dns remote config"
+        STATE=${TF_DIR}/terraform.tfstate
+        ;;
+esac
 echo "Using state file $STATE"
 
 echo "Ensuring ${TF_DIR} is a terraform directory"
 # NOTE: JJG remove trailing slash from $2 if it exists to ease use with auto completion
 if [ ! -f "${TF_DIR}/main.tf" ] ; then
-  die "you must specify a terraform project folder"
+    echo_red "deploy: not found: '${TF_DIR}/main.tf'"
+    echo_red "Are you sure '${TF_DIR}' is a terraform project folder?"
+    echo_red "Known examples include terraform-app, etc."
+    die "error: Could not find terraform files"
 fi
 
 echo "Configuring state bucket login_dot_gov_tf_state with state path ${STATE}"
@@ -74,5 +80,8 @@ cat <<EOF
 #
 ########################################
 EOF
+
+echo_blue "Running terraform..."
+echo
 
 run terraform "${TF_CMD[@]}"
