Added scripts for bootstrapping a new environment (#252)
* Added environment with non user specific presets

Much of this configuration doesn't change user to user and is difficult to
find, so adding it should make this easier to get up and running.

* Remove use of whoami

My local machine does not have the same username as what I should have on the
infrastructure.

* Add GSA_FULLNAME and GSA_EMAIL

This is to avoid having to customize the environment script.

* Programatically set git branch that chef downloads

The chef server clones the identity-devops repo to get the chef cookbooks.
Assume that we want our current working branch to be deployed.

* Add TF_VAR_apps_enabled setting

* Added wrapper script to load environment

This does some basic checks to make sure you have the necessary environment
variables set.

* Remove all CIDR blocks besides GSA from whitelist

Even though we make this configurable, the only approved way to login is
from the GSA internal network, so that's the default.

* Fix rebase issue

There were updates to the way we get AWS power users which were not
reflected when we did the merge.

* Added better documentation

* Use spaces in load env

* Remove settings changes from load-env.sh

Because this file is sourced it messes with the settings of the calling
shell.

* Added scripts for bootstrapping a new environment

See https://github.com/18F/identity-private/issues/1810.

* Create zero elk users by default

This prevents an environment failing on initial bootstrap or having an
unexpected list of users because this file wasn't updated.   Eventually this
should be pulled out into the global config.

* Added kitchen/environments/sverch.json

* Make template_config_dbag.json valid JSON

* Minor style fixes

* Use spaces in check required files

* Minor error message fix

* Adding environment to test this pull request

See https://github.com/18F/identity-devops/pull/252

* Touch a file that terraform expects to exist

* Set first run placeholder for config databag key

* Change environment name

Our scripts fail if the environment name is too long

* Put random contents into chef user key

Apparently terraform complains if there's nothing there.

* Let the first terraform apply fail

* Turn off host key checking

This is not ideal, but we want the bootstrap script to finish

* Only create template files if they do not exist

So that multiple runs don't destroy an existing env

* Make deploy script support all terraform commands

The old script would fail if you passed other options because the
wrapper script didn't pass your arguments to terraform directly.  This
change ensures that terraform gets exactly the same arguments that you
pass to the script so that the wrapper can be used to take advantage of
terraform's full functionality.

* Update README

With this change, most of the steps in the README are automated, so call
that out up front.

* Add warning label to prevent run on existing env

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -3,39 +3,60 @@
 # function to exit process with error message
 die() { echo "$@" 1>&2 ; exit 1; }
 
-: "${TF_VAR_chef_id:?you must specify the TF_VAR_chef_id}"
-: "${TF_VAR_env_name:?you must specify the TF_VAR_env_name}"
+# http://redsymbol.net/articles/unofficial-bash-strict-mode/
+set -euo pipefail
 
-TF_DIR=${2}
+if [ $# -lt 3 ] ; then
+	echo "Usage: $0 <environment name> <username> <terraform_dir> [<terraform_commands>]"
+	exit 1
+fi
 
-if [ -z ${TF_DIR} ]
-  then
-  TF_DIR='terraform-app'
+ENVIRONMENT=$1; shift
+GSA_USERNAME=$1; shift
+TF_DIR=$1; shift
+TF_CMD="$@"
+ENVIRONMENT_CONFIG=env/env.sh
+
+echo "DEPLOY: Loading environment variables...."
+. bin/load-env.sh $ENVIRONMENT $GSA_USERNAME $ENVIRONMENT_CONFIG
+
+echo "DEPLOY: Checking for required files...."
+./bin/check-required-files.sh $ENVIRONMENT
+
+if [ -z "${TF_VAR_chef_id:=}" ] ; then
+    die "You must specify an initial chef user.  \
+Make sure $ENVIRONMENT_CONFIG contains all the necessary configuration."
+fi
+
+if [ -z "${TF_VAR_chef_id:=}" ] ; then
+    die "You must specify an environment to terraform.  \
+Make sure $ENVIRONMENT_CONFIG contains all the necessary configuration."
 fi
 
 STATE=${TF_DIR}/terraform-${TF_VAR_env_name}.tfstate
-
-# Do not use a region specific state file for the dns remote config
-if [ "${TF_DIR}" == "terraform-dns" -o "${TF_DIR}" == "terraform-cloudtrail" ]
-  then
-  STATE=${TF_DIR}/terraform.tfstate
+if [ "${TF_DIR}" == "terraform-dns" -o "${TF_DIR}" == "terraform-cloudtrail" ]; then
+    echo "Not using a region specific state file for dns remote config"
+    STATE=${TF_DIR}/terraform.tfstate
 fi
+echo "Using state file $STATE"
 
-# require one of our terrform plans
+echo "Ensuring ${TF_DIR} is a terraform directory"
 # NOTE: JJG remove trailing slash from $2 if it exists to ease use with auto completion
 if [ ! -f "${TF_DIR}/main.tf" ] ; then
   die "you must specify a terraform project folder"
 fi
 
-# create a s3 bucket based on env_name if one does not exist
-aws s3 mb s3://login_dot_gov_tf_state
+echo "Creating an s3 bucket for terraform state"
+# This command currently fails.
+# See https://github.com/18F/identity-private/issues/1835
+#aws s3 mb s3://login_dot_gov_tf_state
 
-# enable versioning on the s3 bucket
+echo "Enabling versioning on the s3 bucket"
 aws s3api put-bucket-versioning \
   --bucket login_dot_gov_tf_state \
   --versioning-configuration Status=Enabled
 
-# use terraform remote state server
+echo "Using terraform remote state server"
 cd ${TF_DIR}
 rm -rf .terraform
 terraform remote config -backend=s3 \
@@ -44,11 +65,13 @@ terraform remote config -backend=s3 \
   -backend-config="region=us-east-1" \
   -state="${STATE}"
 
-# apply terraform command ($1) to env
-TF_CMD=${1}
-if [ -z $TF_CMD ]
-  then
-  TF_CMD='plan'
-fi
+cat <<EOF
+########################################
+#
+# Working in environment:
+# $TF_VAR_env_name
+#
+########################################
+EOF
 
-terraform ${TF_CMD} -var env_name=${TF_VAR_env_name}
+terraform ${TF_CMD}
