Update id-rails-console to search for current app symlink (#7219)
- We have other rails apps like dashboard, pki, reporting
  but due to the way this is called from ssm-instance, we have
  no straightforward way to pass in an "app" arg, so this
  updates the script to guess

- While we *could* deploy multiple rails apps to the same box,
  in practive we don't, so this should be a pretty safe guess

diff --git a/kitchen/cookbooks/login_dot_gov/templates/default/id-rails-console b/kitchen/cookbooks/login_dot_gov/templates/default/id-rails-console
--- a/kitchen/cookbooks/login_dot_gov/templates/default/id-rails-console
+++ b/kitchen/cookbooks/login_dot_gov/templates/default/id-rails-console
@@ -8,11 +8,11 @@ trap '' 1 2 3 15 19 20
 
 set -eu
 
-app=idp
+app=""
 APP_USER="${APP_USER-websrv}"
 CONSOLE_INFO=()
 
-ENV_VARS=("app=$app")
+ENV_VARS=()
 LOGIN_TASK_LOG_LEVEL='warn'
 
 usage() {
@@ -79,14 +79,24 @@ while [ $# -gt 0 ]; do
     ;;
     *)
       app="$1"
-      if [[ ! -d "/srv/${app}/current" ]] ; then
-        echo "Directory '/srv/${app}/current' not found! Verify app name and run again"
-        exit 1
-      fi
     ;;
   esac
   shift
 done
+
+if [[ -n "$app" && ! -d "/srv/${app}/current" ]] ; then
+  echo "Directory '/srv/${app}/current' not found! Verify app name and run again"
+  exit 1
+elif [[ -z "$app" ]] ; then
+  found_app=$(find /srv -maxdepth 2 -name "current" -type l 2>/dev/null | head -n 1 | cut -d/ -f 3)
+  if [[ -z "$found_app" ]]; then
+    echo "Cound not find a /srv/*/current symlink"
+    exit 1
+  fi
+  app="$found_app"
+fi
+
+ENV_VARS+=("app=$app")
 
 # Pass through ALLOW_CONSOLE_DB_WRITE_ACCESS, if set
 if [ -n "${ALLOW_CONSOLE_DB_WRITE_ACCESS-}" ]; then
