update hashicorp/aws Terraform provider to 5.73.0 (BREAKING)

diff --git a/bin/gitlab-runner/push-gitlab-runner-allowed-images b/bin/gitlab-runner/push-gitlab-runner-allowed-images
--- a/bin/gitlab-runner/push-gitlab-runner-allowed-images
+++ b/bin/gitlab-runner/push-gitlab-runner-allowed-images
@@ -23,7 +23,7 @@ if [[ $rv -ne 0 || ! $aws_account_number ]]; then
   exit 1
 fi
 
-aws_current_region=$(aws configure get region)
+aws_current_region=$(env | grep AWS_REGION | awk -F'=' '{print $NF}')
 
 if [[ $debug -ne 0 || ! $debug ]]; then
   echo "echo $aws_current_region" 1>&2
@@ -91,6 +91,13 @@ if [[ $rv -ne 0 || ! $terraform_plan_image_digest ]]; then
   exit 1
 fi
 
+launch_migration_image_digest=$(sed -n -e '/^[ ]*LAUNCH_MIGRATION_IMAGE_DIGEST/p' .gitlab-ci.yml | cut -d'"' -f2)
+rv="$?"
+if [[ $rv -ne 0 || ! $launch_migration_image_digest ]]; then
+  echo "$pkg: failed to parse output for launch_migration_image_digest" 1>&2
+  exit 1
+fi
+
 aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com
 
 crane copy ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/env_deploy@${deploy_image_digest} ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/env_deploy/blessed@${deploy_image_digest}
@@ -101,3 +108,4 @@ crane copy ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/env_test@${t
 crane copy ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/asg_refresh@${asg_refresh_digest} ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/asg_refresh/blessed@${asg_refresh_digest}
 crane copy ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/devops_terraform_apply@${terraform_apply_image_digest} ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/devops_terraform_apply/blessed@${terraform_apply_image_digest}
 crane copy ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/devops_terraform_plan_verify@${terraform_plan_image_digest} ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/devops_terraform_plan_verify/blessed@${terraform_plan_image_digest}
+crane copy ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/launch_migration@${launch_migration_image_digest} ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/launch_migration/blessed@${launch_migration_image_digest}
diff --git a/bin/gitlab-runner/sign-gitlab-runner-images b/bin/gitlab-runner/sign-gitlab-runner-images
--- a/bin/gitlab-runner/sign-gitlab-runner-images
+++ b/bin/gitlab-runner/sign-gitlab-runner-images
@@ -23,7 +23,7 @@ if [[ $rv -ne 0 || ! $aws_account_number ]]; then
   exit 1
 fi
 
-aws_current_region=$(aws configure get region)
+aws_current_region=$(env | grep AWS_REGION | awk -F'=' '{print $NF}')
 
 if [[ $debug -ne 0 || ! $debug ]]; then
   echo "echo $aws_current_region" 1>&2
@@ -98,6 +98,13 @@ if [[ $rv -ne 0 || ! $terraform_plan_image_digest ]]; then
   exit 1
 fi
 
+launch_migration_image_digest=$(sed -n -e '/^[ ]*LAUNCH_MIGRATION_IMAGE_DIGEST/p' .gitlab-ci.yml | cut -d'"' -f2 | cut -c 8-)
+rv="$?"
+if [[ $rv -ne 0 || ! $launch_migration_image_digest ]]; then
+  echo "$pkg: failed to parse output for launch_migration_image_digest" 1>&2
+  exit 1
+fi
+
 aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com
 
 cosign sign --tlog-upload=false --key "awskms:///alias/image_signing_cosign_signature_key" ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/env_deploy/blessed@sha256:${deploy_image_digest}
@@ -108,3 +115,4 @@ cosign sign --tlog-upload=false --key "awskms:///alias/image_signing_cosign_sign
 cosign sign --tlog-upload=false --key "awskms:///alias/image_signing_cosign_signature_key" ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/asg_refresh/blessed@sha256:${asg_refresh_digest}
 cosign sign --tlog-upload=false --key "awskms:///alias/image_signing_cosign_signature_key"  ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/devops_terraform_apply/blessed@sha256:${terraform_apply_image_digest}
 cosign sign --tlog-upload=false --key "awskms:///alias/image_signing_cosign_signature_key"  ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/devops_terraform_plan_verify/blessed@sha256:${terraform_plan_image_digest}
+cosign sign --tlog-upload=false --key "awskms:///alias/image_signing_cosign_signature_key"  ${aws_account_number}.dkr.ecr.us-west-2.amazonaws.com/cd/launch_migration/blessed@sha256:${launch_migration_image_digest}
